[package]
name = "quick-msm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
ark-bls12-381 = {version = "0.3.0"}
ark-ec = {version = "0.3.0"}
ark-ff = {version = "0.3.0"}
ark-std = {version = "0.3.0"}

[dev-dependencies]
criterion = "0.3"

[profile.test]
opt-level = 3

[[bench]]
harness = false
name = "bench_msm"


